# Generated by Django 5.1 on 2024-10-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coto', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_act',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='supermercado',
        ),
    ]
