# Generated by Django 5.0.6 on 2024-10-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanastaBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
